font_family      FantasqueSansM Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
window_padding_width 4
hide_window_decorations yes

cursor_trail 3

font_size 16.0

background_opacity 0.9

cursor_shape block
shell_integration no-cursor

map F11 toggle_fullscreen

include ./base16-kitty/base16-classic-dark-256.conf
